### ISSUE TITLE
Tri Peaks

### ISSUE THREAD

**Issue by ncs-jeremy** [thecharlesblake/Solvitaire#141]
Is there a tri peaks solver under a different name? I tried looking under other names and didnt see anything.

**Comment by turingfan** [comment]
Hi, unfortunately I don't think our ruleset allows for that kind of pyramidal unhiding scheme.  So we have similar games like Golf or Black Hole, but not ones where the covering is that complex.

**Comment by ncs-jeremy** [comment]
Thanks, I saw some of those games were mentioned as being similar, so was hoping was there under another name maybe.
